# March 17, 2015
# https://docpad.org/docs/deploy
language: node_js
script: "npm test"
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
notifications:
  irc:
    - "irc.freenode.org#bevry-dev"
  email:
    recipients:
      - travisci@bevry.me
